name: fluttera
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  transparent_image: ^1.0.0
  cached_network_image: ^1.1.1
  dio: 3.0.2
  json_annotation: ^3.0.0
  path_provider: ^1.3.1
  image_picker: ^0.6.1+8
#https://github.com/flutterchina/dio
  flutter_aes: ^0.1.1
#https://pub.dev/packages/flutter_aes#-installing-tab-
  flutter_swiper: ^1.1.6
#https://pub.dev/packages/flutter_swiper#-installing-tab-
  flustars: ^0.2.6+1
  #https://github.com/Sky24n/flustars
  dio_cookie_manager: ^1.0.0
  #https://github.com/flutterchina/dio/tree/master/plugins/cookie_manager
  dio_http2_adapter: ^1.0.0
  #https://github.com/flutterchina/dio/tree/master/plugins/http2_adapter
  dio_flutter_transformer: ^3.0.2 # latest version
  #https://github.com/flutterchina/dio_flutter_transformer
  dio_http_cache: ^0.2.1
  #https://github.com/hurshi/dio-http-cache
  retrofit: any

  logger: any  #for logging purpose
  crypto: ^2.0.6
  #https://pub.dev/packages/crypto
  fluttertoast: ^3.1.3
  #https://pub.dev/packages/fluttertoast#-readme-tab-
  flutter_advanced_networkimage: ^0.5.0
#https://pub.dev/packages/flutter_advanced_networkimage#-readme-tab-

  image_jpeg: ^1.1.1
  #https://pub.dev/packages/image_jpeg#-installing-tab-
#  photo: ^0.4.5

  #image: ^2.1.8
  #https://pub.dev/packages/image#-installing-tab-

  #flutter_svg: ^0.14.4
  #https://pub.dev/packages/flutter_svg#-installing-tab-

#  zoomable_image: ^1.2.1
  #https://pub.dev/packages/zoomable_image


#  image_carousel: ^0.4.1
  #https://pub.dev/packages/image_carousel#-installing-tab-


  carousel_slider: ^1.3.1
#https://pub.dev/packages/carousel_slider#-installing-tab-

#  photo: ^0.4.4

  flutter_picker: ^1.1.0
  #https://pub.dev/packages/flutter_picker#-readme-tab-

  flutter_spinkit: "^4.0.0"
  #https://github.com/jogboms/flutter_spinkit

  flutter_staggered_grid_view: "^0.2.7"
#https://pub.dev/packages/flutter_staggered_grid_view

  url_launcher: ^5.2.5
  #https://pub.dev/packages/url_launcher#-installing-tab-
  flutter_msg_engine: ^1.0.0
  #https://pub.dev/packages/flutter_msg_engine#-installing-tab-

  #flutter_html_view: ^0.5.11
  #https://pub.dev/packages/flutter_html_view

  #flutter_html_textview: "^0.2.6"
  #https://pub:dev/packages/flutter_html_textview:

  fluro: "^1.5.1"
  #https://github.com/theyakka/fluro

  rxdart: ^0.22.6
  #https://pub.dev/packages/rxdart#-installing-tab-

  rx_widgets: ^2.5.0
  #https://pub.dev/packages/rx_widgets#-installing-tab-
  #rx_widgets是一个包含基于流的Flutter Widgets和Widget帮助程序/便利类的程序包，它们有助于反应式编程风格，特别是与RxDart和RxCommands结合使用。

  #rx_command: ^4.3.2+1
  #https://pub.dev/packages/rx_command#-installing-tab-
  #RxCommand是针对事件处理程序的基于Reactive Extensions（Rx）的抽象。它基于ReactiveUI框架的ReactiveCommand。它大量使用了RxDart包。

  flutter_cupertino_settings: any
  #https://github.com/matthinc/flutter_cupertino_settings

  flutter_easyrefresh: ^2.0.4
  #https://github.com/xuelongqy/flutter_easyrefresh


  flutter_udid: ^1.0.1
  #https://github.com/GigaDroid/flutter_udid

  flutter_webview_plugin: ^0.3.9+1
  #https://github.com/fluttercommunity/flutter_webview_plugin/

  #flutter_sticky_header: ^0.4.0
  #https://github.com/letsar/flutter_sticky_header

  #https://github.com/renefloor/side_header_list_view

  #https://github.com/fluttercommunity/flutter_infinite_listview


  #https://github.com/xqwzts/flutter_radial_menu


  #https://github.com/hnvn/flutter_flip_panel

#snackbar封装
  #https://github.com/AndreHaueisen/flushbar
  flushbar: ^1.9.1

  #https://github.com/Rahiche/stepper_touch

  #https://github.com/rvamsikrishna/flutter_fluid_slider

  #翻页
  #https://github.com/ariedov/flutter_snaplist
  #https://github.com/Ivaskuu/tinder_cards
  #https://github.com/roughike/page-transformer
  #https://github.com/leocavalcante/page_view_indicator
  #https://github.com/best-flutter/flutter_swiper

  #内容加载时带有微光效果的组件
  #https://github.com/hnvn/flutter_shimmer

  #存储
  #https://github.com/renefloor/flutter_cache_manager
  flutter_cache_manager: ^1.1.3
  #https://github.com/OpenFlutter/mmkv_flutter
  mmkv_flutter: ^1.0.10
  #https://github.com/mogol/flutter_secure_storage
  flutter_secure_storage: ^3.3.1+1
  #https://pub.dev/packages/file_cache
  #file_cache: ^0.1.2

  #下载
  #https://github.com/fluttercommunity/flutter_downloader

  #https://github.com/iampawan/Flutter-UI-Kit
dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
      -  assets/lake.png
      - assets/1.jpeg
      - assets/2.jpeg
      - assets/3.jpeg
      - assets/4.jpeg
      - assets/5.jpeg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
